# Generated by Django 5.1.2 on 2024-12-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='author', max_length=255),
            preserve_default=False,
        ),
    ]
