# Generated by Django 5.1.2 on 2024-12-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='theme',
            field=models.CharField(default='Спорт', max_length=255),
            preserve_default=False,
        ),
    ]
